In [2]:
import pandas as pd
import sqlite3

In [2]:
import os
os.chmod(r"C:\Users\76571\Desktop\stage\data\enpc_2019.txt", 644)
path = os.path.join(r"C:\Users\76571\Desktop\stage\data\enpc_2019.txt")

In [3]:
#lire 10 premier ligne pour savoir des labels
pd.read_csv(r"C:\Users\76571\Desktop\stage\donnees\enpc_2019.txt",delimiter=";",encoding='iso 8859-1',nrows=10)

,COOR_X_PHSQ,COD_RECT,COD_MOD_VALD,LIBL_LONG_MOD,LIBL_NATR_VALD,COD_STF_TRNS,COD_STF_RES,LIBL_STF_LIGN,NUMR_COURSE,IDNT_MISS_RATP,IDNT_VEHC,NUMR_BORN_VALD_EQPM,COD_TLB_ARRT_STTN,JOUR_EXPL_VALD,NUMR_CART,COD_STF_LIGN,COD_NATR_VALD,COOR_Y_PHSQ,LIBL_LONG_ARRT_STTN,HEUR_VALD
0,5.99201435900003E 005,NaN,2,BUS,Entree Bus,100,100,PORTE D'ORLEANS - METRO-CHARCOT - ZOLA,32693,585,1882,5161,30010187005,2019-02-11,28324619970161004008,187,11,1.22752745033534E 005,CROIX D'ARCUEIL,09:16:14 ...
1,5.92758739758578E 005,NaN,2,BUS,Entree Bus,100,100,GARE D'ARGENTEUIL-GARE DE SARTROUVILLE-RER,50810,120,5415,14361,30010272009,2019-02-11,17754583754807690272,272,11,1.37278221182248E 005,PLACE DU 11 NOVEMBRE,17:32:42 ...
2,6.26114337257746E 005,NaN,2,BUS,Entree Bus,62,62,AVON (LES BOULEAUX) - FONTAINEBLEAU (LES LILAS),17,-1,8001,4115,612,2019-02-11,89255867590981351598,61,11,7.85681132102329E 004,DUNANT,14:03:00 ...
3,5.98318032694603E 005,NaN,2,BUS,Entree Bus,100,100,OPERA-PONT DE LEVALLOIS,70090,3004,9847,15096,30010053024,2019-02-11,66148194672078803885,53,11,1.31860471595416E 005,PONT CARDINET,16:34:20 ...
4,5.92758739758578E 005,NaN,2,BUS,Entree Bus,100,100,GARE D'ARGENTEUIL-GARE DE SARTROUVILLE-RER,50676,120,1959,12412,30010272009,2019-02-11,03313363032388172216,272,11,1.37278221182248E 005,PLACE DU 11 NOVEMBRE,09:20:04 ...
5,5.99744140218466E 005,NaN,2,BUS,Entree Bus,100,100,PORTE DE BAGNOLET - LOUIS GANNE-LAPLACE RER,71143,65535,9484,16491,30010057051,2019-02-11,05080169377039544871,57,11,1.23043583823329E 005,LAPLACE RER,09:16:46 ...
6,5.93441997285573E 005,NaN,2,BUS,Entree Bus,100,100,PORTE DE SAINT-CLOUD-GABRIEL PERI-METRO,26292,701,8701,6929,30010175022,2019-02-11,46623649319802419438,175,11,1.31266985044792E 005,SQUARE LEON BLUM,19:01:52 ...
7,5.99201435900003E 005,NaN,2,BUS,Entree Bus,100,100,PORTE D'ORLEANS - METRO-CHARCOT - ZOLA,32800,585,4643,10411,30010187005,2019-02-11,86860311077993969201,187,11,1.22752745033534E 005,CROIX D'ARCUEIL,17:17:52 ...
8,6.38836219630579E 005,NaN,2,BUS,Entree Bus,67,167,MEAUX (Service Urbain),11897,-1,1940,2840,1508,2019-02-11,89528826658810048757,3,11,1.38562830278449E 005,SUCRERIE,07:48:00 ...
9,5.99744140218466E 005,NaN,2,BUS,Entree Bus,100,100,PORTE DE BAGNOLET - LOUIS GANNE-LAPLACE RER,71101,4,9363,5664,30010057051,2019-02-11,19163831060625212747,57,11,1.23043583823329E 005,LAPLACE RER,19:13:42 ...

In [4]:
db=sqlite3.connect('ENPC_data.db')

In [26]:
#lire dans le datebase par chunk
chunks=pd.read_csv(r"C:\Users\76571\Desktop\stage\donnees\enpc_2019.txt",delimiter=";",encoding='iso 8859-1',chunksize=100_000)
for chunk in chunks:
    chunk.to_sql('ENPC',db,if_exists='append')

C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3049: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3049: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3049: DtypeWarning: Columns (6,12) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3049: DtypeWarning: Columns (6,16) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3049: DtypeWarning: Columns (6,12,16) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3049: DtypeWarning: Columns (16) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3049: DtypeWarning: Columns (12,16) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [5]:
db=sqlite3.connect('ENPC_data.db')
#nombre de donnees
pd.read_sql_query('SELECT count(*) FROM ENPC',db)

   count(*)
0  95354835

In [2]:
# 95354835

In [3]:
db=sqlite3.connect('ENPC_data.db')
#nombre de donnees
pd.read_sql_query("SELECT count(*) FROM ENPC WHERE JOUR_EXPL_VALD='2019-02-11'",db)

   count(*)
0  13504282